branches:
  only:
  - master

language: java

services:
  - docker

before_install:
  - npm install --prefix ./client ./client

script:
  - ./server/gradlew -p ./server/ check || travis_terminate 1
  - npm run --prefix ./client build

